### ISSUE TITLE
User Story - User Can Get All Todo Tasks

### ISSUE THREAD

**Issue by Jonpatt92** [Jonpatt92/todo_list#4]
As a User, 
When I visit the task_index page `GET /todos`,
In order to view all of my Todo Tasks,
I see a list of all my 'Complete' Tasks and their Status,
I see a list of all my 'Incomplete' Tasks and their Status.

- [x] All Task names are links to that Task's show page

- [x] Incomplete tasks have a link to 'Complete Task' which triggers the TodoController 'Update' action and marks that task Complete, rerouting back to the task_index page

- [x] There is a link to 'Create a new task'
